import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorial: [
    {
      type: "category",
      label: "开始",
      collapsible: false,
      items: ["index"],
    },
    {
      type: "category",
      label: "基础",
      items: [
        {
          type: "autogenerated",
          dirName: "guide",
        },
      ],
    },
  ],
  api: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
